### ISSUE TITLE
Not working for Laravel v 9 

### ISSUE THREAD

**Issue by madushancs** [apichef/laravel-pay-here#16]
## Description

This package is currently not supported to the new Laravel version 9. I was currently install new Laravel 9 and tried to install this package. But I get errors, 

```
Using version ^2.0 for apichef/laravel-pay-here
./composer.json has been updated
Running composer update apichef/laravel-pay-here
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires apichef/laravel-pay-here ^2.0 -> satisfiable by apichef/laravel-pay-here[v2.0.0, v2.0.1].
    - apichef/laravel-pay-here[v2.0.0, ..., v2.0.1] require illuminate/database ^7.0|^8.0 -> found illuminate/database[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require apichef/laravel-pay-here:*" to figure out if any version is installable, or "composer require apichef/laravel-pay-here:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

## Context

I already used this package and it is super easy and very helpful to develop e-commerce sites thanks to you. So if you can update this package for Laravel 9 it will so great and so awesome.  

## Run environment 

        "Laravel": "9.0",
        "php": "8.1.2",   
        "laravel/jetstream": "^2.6",  
        "livewire/livewire": "^2.5"

**Comment by milroyfraser** [comment]
Hi @madushancs 👋🏼 , Thanks for the issue. 3.0.1 released. Enjoy!

**Comment by madushancs** [comment]
Hey milroyfraser. Thank you very much. Is this package support to the **One-Click Payment** option? Can you upload the video for your youtube channel? It will help a lot of people who use this package.

**Comment by milroyfraser** [comment]
What is **One-Click Payment**? reference, please.

**Comment by madushancs** [comment]
> What is **One-Click Payment**? reference, please.
Hello, Miloyfraser maybe I am wrong but please check this. I got it from Facebook,

Payhere Tokenization සේවාව ඔබේ Business එකටත් නොමිලේම...! 🤩💙
කිසිඳු අමතර ගාස්තුවකින් තොරව ඔබේ ගනුදෙනු සුරක්ෂිතව කරගන්නා අතරම ඔබේ පාරිභෝගිකයන්ට One-Click Payment සේවාව ලබාදෙන්න. 
අදම Payhere Tokenization සේවාව ඔබේ ව්‍යාපාරයටත් එකතු කරගන්න.
Learn more 👉 [https://blog.payhere.lk/are-your-fingers-tired-of.../](https://blog.payhere.lk/are-your-fingers-tired-of.../?fbclid=IwAR3pCLooUI3yf4uIiYOEOlDb9yYIU91zn6UysNuki6vl-mpsO0nMbSYX43Q)
#PayHereTokenization #completelyFREE #BetterExperience #BetterConversions

![image](https://user-images.githubusercontent.com/45415384/154623410-ba97c678-6234-416e-81df-9b0252ae6708.png)
